In [2]:
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()
data = pd.read_csv(io.BytesIO(uploaded['BuyComputer.csv']))

data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Saving BuyComputer.csv to BuyComputer.csv


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [4]:
data

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [6]:
#Declaring X as all columns excluding last
X = data.iloc[:,:-1].values

#Declare label as last column in the source file
Y = data.iloc[:,-1].values

X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [7]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(X,Y ,
                                   random_state=25, 
                                   test_size=0.25, 
                                   shuffle=True)
     

from os import XATTR_SIZE_MAX
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)
     

X_train

array([[-1.74794123,  0.1546519 ],
       [-0.13969655, -0.60069237],
       [ 1.37394551, -1.44319175],
       [ 0.04950871,  0.00939338],
       [ 1.46854813,  2.10111597],
       [ 0.04950871, -0.57164067],
       [-0.80191495,  2.24637449],
       [ 2.0361639 ,  1.72344384],
       [-0.42350443, -0.31017535],
       [-0.23429918, -0.60069237],
       [ 0.14411134,  1.49103022],
       [-0.3289018 ,  1.20051319],
       [-0.70731232, -0.25207194],
       [ 1.09013762, -1.00741621],
       [ 0.80632974,  0.50327233],
       [-1.74794123,  0.41611722],
       [ 1.94156127,  0.88094446],
       [ 0.42791922, -0.48448556],
       [ 0.04950871, -0.60069237],
       [-0.23429918, -1.41414004],
       [-0.04509392,  0.1837036 ],
       [ 0.99553499,  1.83965065],
       [-0.13969655,  1.57818533],
       [-0.61270969, -1.61750196],
       [-1.27492809, -0.45543386],
       [-0.42350443,  1.22956489],
       [-0.42350443, -0.04871002],
       [-0.9911202 ,  1.92680576],
       [ 0.61712448,

In [9]:
X_test

array([[-0.11732603,  0.15441358],
       [-0.11732603, -1.03573063],
       [-0.01873273, -0.36436723],
       [ 0.77001366, -1.06624715],
       [ 1.65735335,  1.77178906],
       [-0.11732603, -0.1507516 ],
       [ 0.27704717,  0.12389706],
       [ 1.06579356, -0.85263152],
       [-0.11732603,  2.13798728],
       [ 0.67142036, -1.37141234],
       [-1.79341211,  0.45957877],
       [-1.10325901, -1.09676367],
       [ 0.17845387, -0.24230116],
       [-1.79341211, -1.34089582],
       [-0.21591932, -0.21178464],
       [ 0.27704717,  0.36802921],
       [-1.30044561,  0.70371091],
       [ 0.86860696, -0.51694982],
       [-0.31451262, -0.21178464],
       [-0.90607242, -0.60849938],
       [-0.11732603,  0.79526047],
       [ 1.16438686, -1.43244537],
       [ 0.86860696,  1.40559084],
       [-0.90607242, -0.73056545],
       [ 1.36157346,  2.1685038 ],
       [-0.41310592, -0.73056545],
       [ 2.15031985, -0.6390159 ],
       [ 0.77001366,  1.52765691],
       [-1.20185231,

In [10]:

#Variabes to calculate sigmoid function
y_pred = []
len_x = len(X_train[0])
w = []
b = 0.2
print(len_x)
     

2


In [11]:
entries = len(X_train[:,0])
   

entries

300

In [12]:
for weights in range(len_x):
  w.append(0)
     
w


[0, 0]

In [13]:
def sigmoid(z):
  return (1/(1+np.exp(-z)))

     

def predict(inputs):
  z=np.dot(inputs,w)+b
  h=sigmoid(z)
  for i in range((len(h))):
    if(h[i]>=0.5):
      h[i]=1
    else:
      h[i]=0
  return h
  

In [14]:
from scipy.optimize.minpack import shape
def loss_func(y,y1):
  total_loss=np.sum(-y*np.log(y1)-(1-y)*np.log(1-y1))
  m=y.shape[0]
  j=total_loss/m
  return j
     

dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
  dw.append(0)
     

l1=[]
for i in range(3000):
    z = np.dot(X_train, w) + b
    y_pred = sigmoid(z)
    l = loss_func(y_train, y_pred)
    l1.append(l)
    dw = np.dot((y_pred-y_train).T, X_train)/X_train.shape[0]
    db = np.mean(y_pred-y_train)
    w = w - alpha * dw
    b = b - alpha* db
    print("Round:",i,"Weight:",w,"Bias:",b,"loss:",l)

<ipython-input-14-db82e2489b52>:1: DeprecationWarning: Please use `shape` from the `scipy.optimize` namespace, the `scipy.optimize.minpack` namespace is deprecated.
  from scipy.optimize.minpack import shape


Round: 0 Weight: [0.0301796  0.01779168] Bias: 0.18134993360208554 loss: 0.7254722027149253
Round: 1 Weight: [0.05955298 0.03504366] Bias: 0.16316346315314978 loss: 0.7099332185396486
Round: 2 Weight: [0.08814111 0.05177184] Bias: 0.14543230294646636 loss: 0.6952233582412951
Round: 3 Weight: [0.11596589 0.0679927 ] Bias: 0.12814732425128014 loss: 0.6812994160210768
Round: 4 Weight: [0.1430499  0.08372307] Bias: 0.11129870344493895 loss: 0.6681189932181743
Round: 5 Weight: [0.16941612 0.09897999] Bias: 0.09487606289318515 loss: 0.6556407945368076
Round: 6 Weight: [0.19508778 0.11378057] Bias: 0.07886860219629804 loss: 0.6438248636801185
Round: 7 Weight: [0.22008809 0.1281418 ] Bias: 0.06326521820709705 loss: 0.6326327627071493
Round: 8 Weight: [0.24444017 0.14208051] Bias: 0.048054612920874214 loss: 0.6220277006223041
Round: 9 Weight: [0.26816681 0.15561322] Bias: 0.0332253889175976 loss: 0.611974617358524
Round: 10 Weight: [0.29129047 0.16875608] Bias: 0.01876613249774943 loss: 0.60244

In [15]:
X_train

array([[-1.74794123,  0.1546519 ],
       [-0.13969655, -0.60069237],
       [ 1.37394551, -1.44319175],
       [ 0.04950871,  0.00939338],
       [ 1.46854813,  2.10111597],
       [ 0.04950871, -0.57164067],
       [-0.80191495,  2.24637449],
       [ 2.0361639 ,  1.72344384],
       [-0.42350443, -0.31017535],
       [-0.23429918, -0.60069237],
       [ 0.14411134,  1.49103022],
       [-0.3289018 ,  1.20051319],
       [-0.70731232, -0.25207194],
       [ 1.09013762, -1.00741621],
       [ 0.80632974,  0.50327233],
       [-1.74794123,  0.41611722],
       [ 1.94156127,  0.88094446],
       [ 0.42791922, -0.48448556],
       [ 0.04950871, -0.60069237],
       [-0.23429918, -1.41414004],
       [-0.04509392,  0.1837036 ],
       [ 0.99553499,  1.83965065],
       [-0.13969655,  1.57818533],
       [-0.61270969, -1.61750196],
       [-1.27492809, -0.45543386],
       [-0.42350443,  1.22956489],
       [-0.42350443, -0.04871002],
       [-0.9911202 ,  1.92680576],
       [ 0.61712448,

In [16]:
Y_pred=predict(X_test)
Y_pred

array([0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0.,
       1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
#print actual and predicted values in a table
print("actual Value\tpredicted values")
for i in range(len(y_test)):
    print(y_test[i],"\t\t",int(y_pred[i]))

actual Value	predicted values
0 		 0
0 		 0
0 		 0
1 		 0
1 		 0
0 		 0
0 		 0
1 		 0
1 		 0
1 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
1 		 0
0 		 0
0 		 0
1 		 0
1 		 0
1 		 0
0 		 0
1 		 0
0 		 0
1 		 0
1 		 0
0 		 0
0 		 0
0 		 0
0 		 0
1 		 0
0 		 0
1 		 0
1 		 0
0 		 0
0 		 0
1 		 0
1 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
1 		 0
0 		 0
0 		 0
0 		 0
1 		 0
0 		 0
1 		 0
1 		 0
0 		 0
0 		 0
0 		 0
1 		 0
1 		 0
0 		 0
0 		 0
0 		 0
0 		 0
1 		 0
0 		 0
0 		 0
0 		 0
1 		 0
1 		 0
0 		 0
1 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
1 		 0
1 		 0
1 		 0
0 		 0
0 		 0
1 		 0
1 		 0
1 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
1 		 0
0 		 0
0 		 0


In [18]:
x=0
for i in range(len(y_test)):
  if(y_test[i]==y_pred[i]):
    x+=1
print((x/len(y_test))*100)

0.0


In [19]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
from sklearn.metrics import  accuracy_score
#Fit
LR.fit(X_train,y_train)

#predicting the test label with LR. Predict always takes X as input
y_test_pred = LR.predict(X_test)
accuracy = accuracy_score(y_test, y_test_pred)*100
print("Accuracy: ", accuracy,"%")

Accuracy:  79.0 %


In [22]:
import matplotlib.pyplot as plt
l1=np.array(l1)

In [24]:
len(l1)
     

3000

In [25]:
l1

array([0.7254722 , 0.70993322, 0.69522336, ..., 0.33411302, 0.33411302,
       0.33411302])

In [31]:
X=np.array(range(0,3000))

In [32]:
X

array([   0,    1,    2, ..., 2997, 2998, 2999])

In [34]:
hello1=np.array([[28,76000]])
hello1=np.array(hello1)
     

hello1

array([[   28, 76000]])

In [35]:
x_ask=sc.fit(hello1)
     

x_ask=x_ask.transform(hello1)
     

x_ask

array([[0., 0.]])

In [36]:

LR.predict(x_ask)
     

array([0])