In [23]:
import numpy as np
random_array = np.random.normal(0.0, 1.0, 100)
random_array

array([ 8.37340921e-01, -2.55781514e-01,  1.72640583e+00, -3.25476229e-01,
        7.21999459e-01, -5.84368235e-03, -2.12763326e-02, -9.90379091e-01,
        4.39637278e-01,  5.15890877e-01,  1.03905166e+00,  2.33002408e-01,
        1.74497571e+00, -9.72245912e-01, -5.83462291e-02, -3.23764710e-01,
       -5.86623573e-01,  3.73599889e-01,  8.61320311e-01, -4.27821165e-01,
        1.33274820e+00,  7.55161697e-01, -2.06623272e-01,  3.75908519e-01,
        2.30338469e+00,  2.63765565e-01,  3.15345191e-01, -1.02945679e+00,
       -6.82578917e-01, -2.42620821e-01, -3.40818329e-01, -3.72157812e-01,
        1.17250217e+00, -2.92925949e+00, -9.75477878e-01, -7.89924916e-01,
        6.30911613e-02,  1.13865175e-01, -2.24392197e+00, -8.39486336e-01,
       -1.08690868e+00, -4.81281940e-01, -4.07574923e-01, -2.66160612e-01,
       -4.88207101e-01, -5.92817161e-01, -2.16512996e+00, -9.81507692e-01,
        4.92971699e-03, -4.76096959e-01, -1.53115629e-01,  5.27290280e-01,
        1.33242477e+00,  

**Create 1D array arr1  with 10 elements.bold text**


---



In [24]:
arr1=np.random.randint(0,10,10)
arr1


array([4, 2, 1, 7, 8, 1, 4, 6, 2, 6])

(a) Slice this array starting from 3rd value to the end.


(b) What is the result if you perform the following slicing on the given array. arr1


---



In [25]:
arr1[3:11]

array([7, 8, 1, 4, 6, 2, 6])

In [26]:
arr1[-4:-2]

array([4, 6])

4. Create two numpy arrays of size 4 x 4. Write functions used to calculate determinant ofmatrix, transpose of a matrix, norm of a matrix and to perform matrix multiplication. Write all the results.


---



In [27]:
m1=np.random.randint(0,20,size=(4,4))
m2=np.random.randint(0,20,size=(4,4))
m1


array([[ 8,  8, 11, 19],
       [19, 17,  7, 15],
       [ 3,  0,  5, 16],
       [ 9,  8, 18,  9]])

In [28]:
m2

array([[ 3, 14,  9,  7],
       [13, 14, 13,  9],
       [ 3, 14, 13,  2],
       [ 8,  9, 11,  2]])

In [29]:
m1*m2

array([[ 24, 112,  99, 133],
       [247, 238,  91, 135],
       [  9,   0,  65,  32],
       [ 72,  72, 198,  18]])

In [30]:
m1.T

array([[ 8, 19,  3,  9],
       [ 8, 17,  0,  8],
       [11,  7,  5, 18],
       [19, 15, 16,  9]])

In [31]:
m2.T

array([[ 3, 13,  3,  8],
       [14, 14, 14,  9],
       [ 9, 13, 13, 11],
       [ 7,  9,  2,  2]])

In [32]:
det = np.linalg.det(m1)
det

11866.000000000011

In [33]:
det = np.linalg.det(m2)
det

129.99999999999903

In [34]:
normByCols = np.linalg.norm(m1, axis=0) # Get the norm for each column.␣
normByRows = np.linalg.norm(m1, axis=1) # get the norm for each row.␣
     

In [35]:
normByCols

array([22.69361144, 20.42057786, 22.7815715 , 30.38091506])

In [36]:
normByRows

array([24.69817807, 30.39736831, 17.02938637, 23.4520788 ])

In [37]:
normByCols = np.linalg.norm(m2, axis=0) # Get the norm for each column.␣
normByRows = np.linalg.norm(m2, axis=1) # get the norm for each row.␣

In [38]:
normByCols


array([15.84297952, 25.86503431, 23.23790008, 11.74734012])

In [39]:
normByRows

array([18.30300522, 24.79919354, 19.4422221 , 16.43167673])

In [42]:
from sklearn.datasets import load_iris

Data=load_iris()
import pandas as pd
df=pd.DataFrame(Data.data, columns=Data.feature_names)
df["target"]=pd.Series(Data.target)
     
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [43]:
X=df.iloc[1:5,:]
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
1       0  
2       0  
3       0  
4       0

In [44]:
X=df.iloc[:,2:5]
X

petal length (cm)  petal width (cm)  target
0                  1.4               0.2       0
1                  1.4               0.2       0
2                  1.3               0.2       0
3                  1.5               0.2       0
4                  1.4               0.2       0
..                 ...               ...     ...
145                5.2               2.3       2
146                5.0               1.9       2
147                5.2               2.0       2
148                5.4               2.3       2
149                5.1               1.8       2

[150 rows x 3 columns]

In [47]:
import nltk # Python library for NLP
from nltk.corpus import twitter_samples # sample Twitter dataset from NLTK
import matplotlib.pyplot as plt # library for visualization
import random
nltk.download('punkt')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [49]:
paragraph="""
I have three visions for India. beautiful In 3000 years of our history people from all over the world have come and invaded us, captured our lands, conquered our minds. From Alexander onwards the Greeks, the Turks, the Moguls, the Portuguese, the British, the French, the Dutch, all of them came and looted us, took over what was ours. Yet we have not done this to any other nation. We have not conquered anyone. We have not grabbed their land, their culture and their history and tried to enforce our way of life on them. Why? Because we respect the freedom of others. That is why my FIRST VISION is that of FREEDOM. I believe that India got its first vision of this in 1857, when we started the war of Independence. It is this freedom that we must protect and nurture and build on. If we are not free, no one will respect us.

We have 10 percent growth rate in most areas. Our poverty levels are falling. Our achievements are being globally recognised today. Yet we lack the self-confidence to see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect? MY SECOND VISION for India is DEVELOPMENT. For fifty years we have been a developing nation. It is time we see ourselves as a developed nation. We are among top five nations in the world in terms of GDP.

I have a THIRD VISION. India must stand up to the world. Because I believe that unless India stands up to the world, no one will respect us. Only strength respects strength. We must be strong not only as a military power but also as an economic power. Both must go hand-in-hand. My good fortune was to have worked with three great minds. Dr.Vikram Sarabhai, of the Dept. of Space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material. I was lucky to have worked with all three of them closely and consider this the great opportunity of my life.
"""
     

In [50]:
sentences=nltk.sent_tokenize(paragraph)

print(sentences)

['\nI have three visions for India.', 'beautiful In 3000 years of our history people from all over the world have come and invaded us, captured our lands, conquered our minds.', 'From Alexander onwards the Greeks, the Turks, the Moguls, the Portuguese, the British, the French, the Dutch, all of them came and looted us, took over what was ours.', 'Yet we have not done this to any other nation.', 'We have not conquered anyone.', 'We have not grabbed their land, their culture and their history and tried to enforce our way of life on them.', 'Why?', 'Because we respect the freedom of others.', 'That is why my FIRST VISION is that of FREEDOM.', 'I believe that India got its first vision of this in 1857, when we started the war of Independence.', 'It is this freedom that we must protect and nurture and build on.', 'If we are not free, no one will respect us.', 'We have 10 percent growth rate in most areas.', 'Our poverty levels are falling.', 'Our achievements are being globally recognised t

In [51]:
word=nltk.word_tokenize(paragraph)

print(word)

['I', 'have', 'three', 'visions', 'for', 'India', '.', 'beautiful', 'In', '3000', 'years', 'of', 'our', 'history', 'people', 'from', 'all', 'over', 'the', 'world', 'have', 'come', 'and', 'invaded', 'us', ',', 'captured', 'our', 'lands', ',', 'conquered', 'our', 'minds', '.', 'From', 'Alexander', 'onwards', 'the', 'Greeks', ',', 'the', 'Turks', ',', 'the', 'Moguls', ',', 'the', 'Portuguese', ',', 'the', 'British', ',', 'the', 'French', ',', 'the', 'Dutch', ',', 'all', 'of', 'them', 'came', 'and', 'looted', 'us', ',', 'took', 'over', 'what', 'was', 'ours', '.', 'Yet', 'we', 'have', 'not', 'done', 'this', 'to', 'any', 'other', 'nation', '.', 'We', 'have', 'not', 'conquered', 'anyone', '.', 'We', 'have', 'not', 'grabbed', 'their', 'land', ',', 'their', 'culture', 'and', 'their', 'history', 'and', 'tried', 'to', 'enforce', 'our', 'way', 'of', 'life', 'on', 'them', '.', 'Why', '?', 'Because', 'we', 'respect', 'the', 'freedom', 'of', 'others', '.', 'That', 'is', 'why', 'my', 'FIRST', 'VISION'

In [52]:
# Remove stop words and punctuations
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [53]:
import re
import string # for string operations
from nltk.corpus import stopwords # module for stop words that come␣

from nltk.stem import PorterStemmer # module for stemming
from nltk.tokenize import TweetTokenizer # module for tokenizing strings
from nltk.stem import WordNetLemmatizer

stopwords_english = stopwords.words('english')
print('Stop words\n')
print(stopwords_english)
print('\nPunctuation\n')
print(string.punctuation)

Stop words

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so

In [54]:
word_clean = []
word=nltk.word_tokenize(paragraph)
for x in word:
  if (x not in stopwords_english and x not in string.punctuation): # remove punctuation
      word_clean.append(x)
   # Go through every word in your tokens list

print('removed stop words and punctuation:')
print(word_clean)

removed stop words and punctuation:
['I', 'three', 'visions', 'India', 'beautiful', 'In', '3000', 'years', 'history', 'people', 'world', 'come', 'invaded', 'us', 'captured', 'lands', 'conquered', 'minds', 'From', 'Alexander', 'onwards', 'Greeks', 'Turks', 'Moguls', 'Portuguese', 'British', 'French', 'Dutch', 'came', 'looted', 'us', 'took', 'Yet', 'done', 'nation', 'We', 'conquered', 'anyone', 'We', 'grabbed', 'land', 'culture', 'history', 'tried', 'enforce', 'way', 'life', 'Why', 'Because', 'respect', 'freedom', 'others', 'That', 'FIRST', 'VISION', 'FREEDOM', 'I', 'believe', 'India', 'got', 'first', 'vision', '1857', 'started', 'war', 'Independence', 'It', 'freedom', 'must', 'protect', 'nurture', 'build', 'If', 'free', 'one', 'respect', 'us', 'We', '10', 'percent', 'growth', 'rate', 'areas', 'Our', 'poverty', 'levels', 'falling', 'Our', 'achievements', 'globally', 'recognised', 'today', 'Yet', 'lack', 'self-confidence', 'see', 'developed', 'nation', 'self-reliant', 'self-assured', 'Isn

**STENNING**

---



In [55]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
     

stemmer=PorterStemmer()
     

paragraph="""Pythoners are very intelligent and work very pythonly and now they are pythoning their way to success."""
     

word=nltk.word_tokenize(paragraph)
     

word
     

['Pythoners',
 'are',
 'very',
 'intelligent',
 'and',
 'work',
 'very',
 'pythonly',
 'and',
 'now',
 'they',
 'are',
 'pythoning',
 'their',
 'way',
 'to',
 'success',
 '.']

In [58]:

steam_clean=[]
for x in word:
  steam_word=stemmer.stem(x)
  steam_clean.append(steam_word)

steam_clean

['python',
 'are',
 'veri',
 'intellig',
 'and',
 'work',
 'veri',
 'pythonli',
 'and',
 'now',
 'they',
 'are',
 'python',
 'their',
 'way',
 'to',
 'success',
 '.']

In [59]:

words =['happier','happiness','happy','studying','study','studies','meeting']


steam_clean2=[]
for word in words:
  stem_word=stemmer.stem(word)
  steam_clean2.append(stem_word)

steam_clean2

['happier', 'happi', 'happi', 'studi', 'studi', 'studi', 'meet']

In [60]:

from nltk.stem import WordNetLemmatizer
     

nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [61]:

wordnet_lemmatizer = WordNetLemmatizer()
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [62]:

x_lem = []
for word in words:
  lem_words = wordnet_lemmatizer.lemmatize(word)# stemming word
  x_lem.append(lem_words) #
     

x_lem

['happier', 'happiness', 'happy', 'studying', 'study', 'study', 'meeting']

In [63]:
paragraph="""
I have three visions for India. beautiful In 3000 years of our history people from all over the world have come and invaded us, captured our lands, conquered our minds. From Alexander onwards the Greeks, the Turks, the Moguls, the Portuguese, the British, the French, the Dutch, all of them came and looted us, took over what was ours. Yet we have not done this to any other nation. We have not conquered anyone. We have not grabbed their land, their culture and their history and tried to enforce our way of life on them. Why? Because we respect the freedom of others. That is why my FIRST VISION is that of FREEDOM. I believe that India got its first vision of this in 1857, when we started the war of Independence. It is this freedom that we must protect and nurture and build on. If we are not free, no one will respect us.

We have 10 percent growth rate in most areas. Our poverty levels are falling. Our achievements are being globally recognised today. Yet we lack the self-confidence to see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect? MY SECOND VISION for India is DEVELOPMENT. For fifty years we have been a developing nation. It is time we see ourselves as a developed nation. We are among top five nations in the world in terms of GDP.

I have a THIRD VISION. India must stand up to the world. Because I believe that unless India stands up to the world, no one will respect us. Only strength respects strength. We must be strong not only as a military power but also as an economic power. Both must go hand-in-hand. My good fortune was to have worked with three great minds. Dr.Vikram Sarabhai, of the Dept. of Space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material. I was lucky to have worked with all three of them closely and consider this the great opportunity of my life.
"""

In [64]:

word=nltk.word_tokenize(paragraph)
     

x_lem = []
for x in word:
  lem_words = wordnet_lemmatizer.lemmatize(x)# stemming word
  x_lem.append(lem_words)
     

x_lem

['I',
 'have',
 'three',
 'vision',
 'for',
 'India',
 '.',
 'beautiful',
 'In',
 '3000',
 'year',
 'of',
 'our',
 'history',
 'people',
 'from',
 'all',
 'over',
 'the',
 'world',
 'have',
 'come',
 'and',
 'invaded',
 'u',
 ',',
 'captured',
 'our',
 'land',
 ',',
 'conquered',
 'our',
 'mind',
 '.',
 'From',
 'Alexander',
 'onwards',
 'the',
 'Greeks',
 ',',
 'the',
 'Turks',
 ',',
 'the',
 'Moguls',
 ',',
 'the',
 'Portuguese',
 ',',
 'the',
 'British',
 ',',
 'the',
 'French',
 ',',
 'the',
 'Dutch',
 ',',
 'all',
 'of',
 'them',
 'came',
 'and',
 'looted',
 'u',
 ',',
 'took',
 'over',
 'what',
 'wa',
 'ours',
 '.',
 'Yet',
 'we',
 'have',
 'not',
 'done',
 'this',
 'to',
 'any',
 'other',
 'nation',
 '.',
 'We',
 'have',
 'not',
 'conquered',
 'anyone',
 '.',
 'We',
 'have',
 'not',
 'grabbed',
 'their',
 'land',
 ',',
 'their',
 'culture',
 'and',
 'their',
 'history',
 'and',
 'tried',
 'to',
 'enforce',
 'our',
 'way',
 'of',
 'life',
 'on',
 'them',
 '.',
 'Why',
 '?',
 'Bec

In [74]:
##1Create Two numpy array of size 4 X 5 and 5 X 4.
import numpy as np
import random as rand
     


In [75]:
arra1=np.array(np.arange(0,20).reshape(5,4))
arra2=np.array(np.arange(0,20).reshape(4,5))

In [76]:
arra1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [77]:
arra2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [78]:
#2.Randomly Initalize that array
array=np.random.randint(1, 100, size=(4, 5))
array

array([[11, 93,  6, 38, 30],
       [97, 70, 55, 91, 53],
       [10, 71, 74, 47, 64],
       [15, 73, 85, 29, 93]])

In [79]:
#3.Perform matrix multiplication
     

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(np.dot(x, y))

[[19 22]
 [43 50]]


In [80]:
print(np.dot(arra1,arra2))

[[ 70  76  82  88  94]
 [190 212 234 256 278]
 [310 348 386 424 462]
 [430 484 538 592 646]
 [550 620 690 760 830]]


In [81]:
#4.4) Perform elementwise matrix multiplication
print(np.multiply(arra1,arra1))

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]
 [256 289 324 361]]


In [82]:
#5.Find mean, median of the first matrix.
np.mean(arra1)

9.5

In [83]:
arra1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [84]:
np.mean(arra1,axis=0)


array([ 8.,  9., 10., 11.])

In [85]:
np.mean(arra1,axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [86]:
np.median(arra1)

9.5

In [87]:
np.median(arra1,axis=0)

array([ 8.,  9., 10., 11.])

In [88]:
np.median(arra1,axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [89]:
#6.Get the transpose of that Matrix that you created. Create a square matrix and find its deter-
#minant.
print(arra1.T)

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


In [93]:
# square matrix 3*3
array3=np.array([[1,2,3],[4,5,6],[7,8,9]])

array3


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
np.linalg.det(array3)

0.0

In [95]:
#Obtain each row in the second column of the first array.
array3[:,1]

array([2, 5, 8])

In [101]:
#8.Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version
import pandas as pd
import numpy as np
data=pd.read_csv('/content/sample_data/mtcars.csv',usecols=['mpg',	'cyl',	'disp'	,'hp'	,'drat',	'wt'	,'qsec'	,'vs','am','gear','carb'])

In [103]:

array1=np.array(data)
array1

array([[ 21.   ,   6.   , 160.   , 110.   ,   3.9  ,   2.62 ,  16.46 ,
          0.   ,   1.   ,   4.   ,   4.   ],
       [ 21.   ,   6.   , 160.   , 110.   ,   3.9  ,   2.875,  17.02 ,
          0.   ,   1.   ,   4.   ,   4.   ],
       [ 22.8  ,   4.   , 108.   ,  93.   ,   3.85 ,   2.32 ,  18.61 ,
          1.   ,   1.   ,   4.   ,   1.   ],
       [ 21.4  ,   6.   , 258.   , 110.   ,   3.08 ,   3.215,  19.44 ,
          1.   ,   0.   ,   3.   ,   1.   ],
       [ 18.7  ,   8.   , 360.   , 175.   ,   3.15 ,   3.44 ,  17.02 ,
          0.   ,   0.   ,   3.   ,   2.   ],
       [ 18.1  ,   6.   , 225.   , 105.   ,   2.76 ,   3.46 ,  20.22 ,
          1.   ,   0.   ,   3.   ,   1.   ],
       [ 14.3  ,   8.   , 360.   , 245.   ,   3.21 ,   3.57 ,  15.84 ,
          0.   ,   0.   ,   3.   ,   4.   ],
       [ 24.4  ,   4.   , 146.7  ,  62.   ,   3.69 ,   3.19 ,  20.   ,
          1.   ,   0.   ,   4.   ,   2.   ],
       [ 22.8  ,   4.   , 140.8  ,  95.   ,   3.92 ,   3.15 ,  22.9  ,
 

In [104]:

nparrayCentered = array1.T - np.mean(array1, axis=1) # Remove the mean for␣
##,→each row
nparrayCentered = nparrayCentered.T #
     

nparrayCentered

array([[-8.90727273e+00, -2.39072727e+01,  1.30092727e+02,
         8.00927273e+01, -2.60072727e+01, -2.72872727e+01,
        -1.34472727e+01, -2.99072727e+01, -2.89072727e+01,
        -2.59072727e+01, -2.59072727e+01],
       [-8.98136364e+00, -2.39813636e+01,  1.30018636e+02,
         8.00186364e+01, -2.60813636e+01, -2.71063636e+01,
        -1.29613636e+01, -2.99813636e+01, -2.89813636e+01,
        -2.59813636e+01, -2.59813636e+01],
       [-7.98181818e-01, -1.95981818e+01,  8.44018182e+01,
         6.94018182e+01, -1.97481818e+01, -2.12781818e+01,
        -4.98818182e+00, -2.25981818e+01, -2.25981818e+01,
        -1.95981818e+01, -2.25981818e+01],
       [-1.73395455e+01, -3.27395455e+01,  2.19260455e+02,
         7.12604545e+01, -3.56595455e+01, -3.55245455e+01,
        -1.92995455e+01, -3.77395455e+01, -3.87395455e+01,
        -3.57395455e+01, -3.77395455e+01],
       [-3.49645455e+01, -4.56645455e+01,  3.06335455e+02,
         1.21335455e+02, -5.05145455e+01, -5.02245455e+01,
  

In [115]:
import numpy as np
import matplotlib as plt
from sklearn import datasets #various toy datasets
from sklearn import metrics #Check accuracy of model
from sklearn.linear_model import LogisticRegression #various supervised and␣
##,→unsupervised learning algorithms

In [116]:
hello = datasets.load_breast_cancer()

In [117]:
X = hello.data
y = hello.target
feature_names = hello.feature_names


target_names = hello.target
print("Feature names:", feature_names)
print("Target names:", target_names)
print("\nFirst 10 rows of X:\n", X[:10])

Feature names: ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
Target names: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 

In [118]:
from sklearn.model_selection import train_test_split

In [119]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size = 0.4, random_state=1
)